INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (92, 53, 'Улица: Васичкин<BR>Дом № 59<BR>Корпус № 22<BR>Квартира № 554<BR>Этаж № 2<BR>', 'lndalgabdvkabcvjabdj');
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (94, 53, 'Улица: Васичкин<BR>Дом № 59<BR>Корпус № 22<BR>Квартира № 554<BR>Этаж № 2<BR>', 1111);
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (95, 53, 'Улица: Васичкин<BR>Дом № 59<BR>Корпус № 22<BR>Квартира № 15<BR>Этаж № 2<BR>', 1111);
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (96, 53, 'Улица: Васичкин<BR>Дом № 59<BR>Корпус № 22<BR>Квартира № 15<BR>Этаж № 2<BR>', 1111);
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (97, 53, 'Улица: Васичкин<BR>Дом № 59<BR>Корпус № 22<BR>Квартира № 15<BR>Этаж № 2<BR>', 1111);
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (91, 52, 'Улица: Тупкин<BR>Дом № 59<BR>Корпус № 22<BR>Квартира № 554<BR>Этаж № 2<BR>', 'Хочу большой Бургер ююююю');
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (93, 52, 'Улица: Тупкин<BR>Дом № 59<BR>Корпус № 22<BR>Квартира № 554<BR>Этаж № 2<BR>', 'Хочу большой Бургер ююююю');
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (90, 51, 'Улица: Тупкин<BR>Дом № 59<BR>Корпус № 22<BR>Квартира № 554<BR>Этаж № 2<BR>', 'Хочу большой Бургер ююююю');
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (89, 50, 'Улица: Тупкин<BR>Дом № 59<BR>Корпус № 22<BR>Квартира № 554<BR>Этаж № 2<BR>', 'Хочу большой Бургер ююююю');
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (88, 49, 'Улица: Тупкин<BR>Дом № 59<BR>Корпус № 22<BR>Квартира № 554<BR>Этаж № 2<BR>', 'Хочу большой Бургер ююююю');
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (87, 48, 'Улица: Тупкин<BR>Дом № 59<BR>Корпус № 22<BR>Квартира № 554<BR>Этаж № 2<BR>', 'Хочу большой Бургер');
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (85, 47, 'Улица: Тупкин<BR>Дом № 59<BR>Корпус № 22<BR>Квартира № 554<BR>Этаж № 2<BR>', 'Хочу большой Бургер');
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (86, 47, 'Улица: Тупкин<BR>Дом № 59<BR>Корпус № 22<BR>Квартира № 554<BR>Этаж № 2<BR>', 'Хочу большой Бургер');
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (79, 46, 'Улица: Пупкин<BR>Дом № 104<BR>Корпус № 102<BR>Квартира № 108<BR>Этаж № 108<BR>', 'kjdvlka;kln000000');
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (80, 46, 'Улица: Пупкин<BR>Дом № 104<BR>Корпус № 102<BR>Квартира № 108<BR>Этаж № 108<BR>', 'kjdvlka;kln000000');
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (81, 46, 'Улица: Пупкин<BR>Дом № 104<BR>Корпус № 102<BR>Квартира № 108<BR>Этаж № 108<BR>', 'kjdvlka;kln000000');
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (82, 46, 'Улица: Пупкин<BR>Дом № 104<BR>Корпус № 102<BR>Квартира № 108<BR>Этаж № 108<BR>', 'kjdvlka;kln000000');
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (83, 46, 'Улица: Пупкин<BR>Дом № 104<BR>Корпус № 102<BR>Квартира № 108<BR>Этаж № 108<BR>', 'kjdvlka;kln000000');
INSERT INTO bdvp1.deliveryusers (id, user_id, adress, commit) VALUES (84, 46, 'Улица: Пупкин<BR>Дом № 104<BR>Корпус № 102<BR>Квартира № 108<BR>Этаж № 108<BR>', 'kjdvlka;kln000000');
